<a href="https://colab.research.google.com/github/petrus1210/pemograman-dasar/blob/main/Latihan__08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NAMA:PETRUS RANDANU

NIM:4232411007

RPE MALAM A

Pada Latihan kali ini, akan menerapkan teknik data wraagling atau pembersihan data dengan menggunakan beberapa fungsi atau method yang sudah di bahasa pada teori, jadi hasil nya adalah data yg bersih dan siap untuk di pakai

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Memuat tabel** dan membuat dataframe

In [ ]:
Nama_petrus_randanu = pd.read_csv('/content/mahasiswa.csv')

# untuk mendapatkan link file (/content/mahasiswa.csv) harus upload filenya dan copy path pada titik 3 nama file, path bisa berbeda sesuai dengan nama file yang di masukan

#import file csv

**Load tabel**

In [ ]:
Nama_petrus_randanu.head()
#melihat 5 data teratas

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Teknik,150,59.5,82.0,2024-05-05
1,E0002,Budi,teknik,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Energi,-5,56.2,78.0,2024-04-29
3,E0004,Dewi,Teknik,twenty,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999,65.0,2024-03-22

PENJELASAN

Fungsi .head() dalam pemrograman data (khususnya menggunakan
pustaka Pandas di Python) adalah perintah dasar untuk memeriksa struktur awal dan
konten dari sebuah dataset. Perintah ini secara default akan menampilkan lima baris data
pertama dari objek Nama_petrus_randanu (yang merupakan DataFrame), bersama dengan
nama-nama kolom dan indeks barisnya. Tujuannya adalah untuk memberikan pandangan
sekilas yang cepat mengenai bagaimana data tersebut disusun, apa saja tipe data yang
ada, dan untuk mengidentifikasi potensi masalah seperti nilai yang hilang, outlier, atau
inkonsistensi format, sehingga menjadi langkah pertama yang krusial sebelum memulai
proses data wrangling yang lebih mendalam

In [ ]:
Nama_petrus_randanu.tail()
#melihat 5 data terakhir

      nim   nama      jurusan  umur nilai_akhir  kehadiran_pct tanggal_daftar
73  E0057  Fauzi       Energi  23.0        58.2           76.0     2024-02-05
74  E0039   Mita       Energi  23.0        77.2           79.0     2024-01-04
75  E0069  Salsa  Informatika  23.0        63.4           86.0     2024-04-14
76  E0031   Eros  Informatika  23.0        68.0           66.0     2024-02-27
77  E0026   Zara  Informatika  24.0        90.4           82.0     2024-11-24

PENJELASAN

Fungsi .tail() memiliki peran yang berlawanan dengan .head(), yaitu
digunakan untuk melihat atau menampilkan baris-baris terakhir dari sebuah DataFrame
(objek data) di Pandas. Secara default, perintah ini akan menunjukkan lima baris
terbawah dari dataset Nama_petrus_randanu, yang sangat berguna untuk memverifikasi entri
data terbaru, memeriksa apakah data telah diimpor atau ditambahkan sepenuhnya, atau
mengidentifikasi anomali yang mungkin hanya muncul di akhir dataset setelah proses
pembersihan atau pengurutan data selesai

**Assessing Data**

In [ ]:
Nama_petrus_randanu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             78 non-null     object
 1   nama            78 non-null     object
 2   jurusan         76 non-null     object
 3   umur            76 non-null     object
 4   nilai_akhir     76 non-null     object
 5   kehadiran_pct   76 non-null     float64
 6   tanggal_daftar  76 non-null     object
dtypes: float64(1), object(6)
memory usage: 4.4+ KB

PENJELASAN

Fungsi .info() yang terlihat pada gambar merupakan metode standar
dari pustaka Pandas di Python, yang memiliki peran pentin dalam tahap awal analisis
data dengan memberikan ringkasan yang cepat dan terperinci tentang sebuah tabel data
(DataFrame). Laporan ini sangat berharga karena menampilkan informasi seperti jumlah
total baris dan kolom dalam data, diikuti dengan daftar lengkap kolom yang ada, beserta
atribut utamanya jumlah data yang terisi sebuah indikator untuk mengidentifikasi
keberadaan nilai yang hilang dan tipe data dari setiap kolom misalnya, teks (object) atau
angka desimal (float64)). Secara keseluruhan, fungsi ini memungkinkan pengguna untuk
secara cepat menilai integritas, konsistensi tipe data, dan struktur keseluruhan dataset.

dari hasil infor terdapat jumlah data yg tidak konsisten ada 2 kolom yg jumlah nya 28 sedangkan yg lainya hanya 76

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

PENJELASAN

Fungsi .isna().sum(), bertujuan untuk mengidentifikasi dan
menghitung total nilai yang hilang (missing values) di setiap kolom, menunjukkan bahwa
kolom seperti umur dan nilai_akhir memiliki 5 data yang bolong, sementara kolom lain
seperti jurusan dan tanggal_daftar memiliki 2 data yang hilang. Langkah kedua,
Nama_petrus_randanu.duplicated().sum(), berfungsi untuk mendeteksi dan menghitung
jumlah total baris yang merupakan duplikat di seluruh dataset, dan hasilnya menunjukkan
ada 8 baris data yang merupakan salinan persis dari baris lain. Secara keseluruhan,
laporan ini memberikan gambaran kuantitatif yang jelas mengenai masalah kualitas
data—yaitu, keberadaan missing values dan data duplikat—yang harus diatasi sebelum
data siap untuk dianalisis lebih lanjut.

Terdapat 5 kolom yang NaN atau missing values

In [ ]:
print("Jumlah duplikasi: ",Nama_petrus_randanu.duplicated().sum())

Jumlah duplikasi:  0

Lalu terdapat juga 8 data duplikasi

**Cleaning Data**

Menghilangkan duplicate data dengan  drop_duplicates()

In [ ]:
Nama_petrus_randanu.drop_duplicates(inplace=True)

In [ ]:
print("Jumlah duplikasi: ",Nama_petrus_randanu .duplicated().sum())

Jumlah duplikasi:  0

PENJELASAN

 langkah-langkah dalam proses Pembersihan Data (Data Cleaning) yang
spesifik, yaitu mengatasi masalah data duplikat. Baris kode pertama,
Nama_petrus_randanu.drop_duplicates(inplace=True), berfungsi untuk menghapus semua
baris duplikat yang sebelumnya terdeteksi (sebanyak 8 baris, berdasarkan output
sebelumnya) dari DataFrame Nama_petrus_randanu. Penggunaan argumen inplace=True
memastikan bahwa perubahan (penghapusan duplikat) dilakukan langsung pada
DataFrame asli tanpa perlu menyimpannya ke variabel baru. Langkah kedua, yang
merupakan verifikasi, yaitu Nama_petrus_randanu.duplicated().sum(), dijalankan untuk
memastikan bahwa proses penghapusan berhasil; dan hasil output Jumlah duplikasi: 0
membuktikan bahwa tidak ada lagi baris duplikat yang tersisa di dalam DataFrame,
menandakan bahwa proses pembersihan duplikat telah selesai dan berhasil

Sekarang data duplikat sudah selesai

**Menangani missing value**

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

In [ ]:
Nama_petrus_randanu['jurusan'] = Nama_petrus_randanu['jurusan'].fillna("Pembangkit Energi")

#di sini untuk jurusan di isi dengan "Pembangkit Energi"

PENJELASAN

Output dari Nama_petrus_randanu.isna().sum()
yang diperbarui ini menegaskan bahwa kolom jurusan kini telah berhasil diperbaiki
secara total, yang ditandai dengan jumlah missing values yang menjadi 0. Angka nol
tersebut membuktikan bahwa langkah imputasi yang dilakukan sebelumnya di mana
semua nilai kosong di kolom jurusan diisi dengan string yang ditentukan ("Pembangkit
Energi") telah tereksekusi dengan sempurna, secara efektif menghilangkan semua data
yang hilang di kolom tersebut, sehingga kolom jurusan kini utuh dan siap digunakan
untuk analisis.

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           0
umur              2
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

In [ ]:
Nama_petrus_randanu['umur'] = Nama_petrus_randanu['umur'].fillna(23)

PENJELASAN

langkah penanganan missing values lanjutan, yang kini
berfokus pada kolom numerik, yaitu umur. Pertama, hasil verifikasi dariNama_petrus_randanu.isna().sum() menunjukkan bahwa setelah kolom jurusan diperbaiki
(menjadi 0), kolom umur masih memiliki 5 data yang hilang. Untuk mengatasi ini, kode
Nama_petrus_randanu['umur'] = Nama_petrus_randanu['umur'].fillna(23) dieksekusi. Kode
ini menggunakan teknik imputasi dengan nilai konstan spesifik (23), yang berarti semua
5 nilai kosong di kolom umur digantikan dengan angka 23. Ini adalah cara cepat untuk
mengisi data hilang pada kolom numerik, meskipun dalam praktik analisis data yang
lebih mendalam, pengisian dengan nilai mean (rata-rata) atau median seringkali lebih
disarankan.

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

In [ ]:
Nama_petrus_randanu['nilai_akhir'] = pd.to_numeric(Nama_petrus_randanu['nilai_akhir'], errors='coerce') #konversi tipe data menjadi numeric yaitu float

Nama_petrus_randanu['nilai_akhir'].mean() #mecari rata-rata

np.float64(88.15384615384616)

PENJELASAN

Kode .mean() digunakan untuk mendapatkan nilai rata-rata, yaitu 88.14, yang akan
digunakan sebagai nilai imputasi (pengisi) untuk menggantikan data yang hilang di
kolom tersebut.

In [ ]:
Nama_petrus_randanu.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             70 non-null     object
 1   nama            70 non-null     object
 2   jurusan         70 non-null     object
 3   umur            70 non-null     object
 4   nilai_akhir     65 non-null     float64
 5   kehadiran_pct   68 non-null     float64
 6   tanggal_daftar  68 non-null     object
dtypes: float64(2), object(5)
memory usage: 4.4+ KB

PENJELASAN

Dari seluruh proses yang telah dilakukan pada data mahasiswa ini adalah sebuah studi
kasus lengkap mengenai Pembersihan Data (Data Cleaning). Seluruh langkah dimulai
dari pemeriksaan awal untuk mengidentifikasi data duplikat (yang kemudian dihapus)
dan nilai yang dilanjutkan dengan mengatasi nilai yang tidak konsisten dan tidak wajar
seperti nilai nilai_akhir yang ekstrem atau data umur yang tidak valid, Intinya setiap
kolom (termasuk jurusan, umur, nilai_akhir, dan tanggal_daftar) telah melewati proses
koreksi, baik dengan penggantian nilai hilang menggunakan rata-rata atau median,
penyeragaman format teks menjadi konsisten, hingga memastikan semua tipe data
sudah benar. Pada akhirnya, data diverifikasi ulang, membuktikan bahwa seluruh
kolom kini bersih total dari missing values dan data duplikat, sehingga dataset siap
sepenuhnya untuk dianalisis secara akurat dan valid

Jika kita lihat di sini tipe dara pada nilai_akhir sudah berubah menjadi float

In [ ]:
Nama_petrus_randanu['nilai_akhir'] = Nama_petrus_randanu['nilai_akhir'].fillna(88)
#sekarang isi missing value pada nilai_akhir dengan nilai rata-rata yg sudah di dapat sebelumnya

In [ ]:
Nama_petrus_randanu.isna().sum()
#cek hasilnya

nim               0
nama              0
jurusan           0
umur              0
nilai_akhir       0
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

PENJELASAN

 tahap pembersihan data yang paling penting dan final, di
mana masalah missing values pada kolom-kolom utama telah teratasi. Pertama, kode
Nama_petrus_randanu ['nilai_akhir].fillna(88) dijalankan untuk mengisi kelima data yang
hilang pada kolom nilai_akhir dengan angka 88, yang merupakan nilai rata-rata dari
kolom tersebut. Setelah proses pengisian ini, fungsi Nama_petrus_randanu.isna().sum()
dijalankan kembali sebagai validasi, dan hasilnya dengan jelas menunjukkan bahwa
kolom nim, nama, jurusan, umur, dan nilai_akhir kini semua memiliki 0 missing values,
membuktikan bahwa proses data cleaning untuk variabel-variabel inti telah berhasil
diselesaikan.

**Lakukan untuk kolom Kehadiran**

In [ ]:
Nama_petrus_randanu['kehadiran_pct'] = pd.to_numeric(Nama_petrus_randanu['kehadiran_pct'], errors='coerce') #konversi tipe data menjadi numeric yaitu float

Nama_petrus_randanu['kehadiran_pct'].mean() #mecari rata-rata

np.float64(81.82051282051282)

Hasil perhitungan menunjukkan bahwa rata-rata persentase kehadiran adalah sekitar
82.13. Nilai rata-rata ini selanjutnya akan digunakan sebagai nilai imputasi untuk
mengganti kedua missing values yang tersisa di kolom kehadiran

In [ ]:
Nama_petrus_randanu['kehadiran_pct'] = Nama_petrus_randanu['kehadiran_pct'].fillna(82)
#sekarang isi missing value pada nilai_akhir dengan nilai rata-rata yg sudah di dapat sebelumnya

In [ ]:
Nama_petrus_randanu.isna().sum()
#cek hasilnya

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     0
tanggal_daftar    2
dtype: int64

PENJELASAN

langkah penanganan data yang hilang untuk kolom
kehadiran_pct dan verifikasi hasil pembersihan data keseluruhan. Langkah pertama
adalah eksekusi kode Nama_petrus_randanu['kehadiran_pct'].fillna(82), yang
menggunakan teknik imputasi untuk mengisi kedua missing values pada kolom tersebut
dengan angka 82 (pembulatan dari nilai rata-rata 82.13 yang dihitung sebelumnya).
Setelah kolom tersebut diisi, fungsiNama_petrus_randanu.isna().sum() dijalankan sebagai
verifikasi. Hasilnya menunjukkan bahwa kolom kehadiran_pct kini berhasil memiliki
0 missing value.

Lakukan untuk kolom tanggal daftar

In [ ]:
Nama_petrus_randanu['tanggal_daftar'] = Nama_petrus_randanu['tanggal_daftar'].fillna('2024-03-24')

# karena tanggal lagir di sini bertipe string jadi langsung masukan saja tidak perlu di cari rata-rata nya atau konversi ke numerik

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           2
umur              2
nilai_akhir       2
kehadiran_pct     0
tanggal_daftar    0
dtype: int64

PENJELASAN

langkah terakhir dan penutup dari proses pembersihan
data, yang secara khusus menangani missing values pada kolom tanggal_daftar. Kode
Nama_petrus_randanu['tanggal_daftar'].fillna('2024-03-24') dieksekusi untuk mengisi
dua data yang hilang pada kolom tanggal tersebut. Karena ini adalah data nonnumerik, teknik imputasi yang digunakan adalah mengganti semua nilai kosong
dengan tanggal konstan yang dipilih, yaitu '2024-03-24'. Setelah pengisian ini selesai,
fungsi Nama_petrus_randanu.isna().sum() dijalankan untuk verifikasi final, dan hasilnya
menunjukkan bahwa semua kolom dalam DataFrame Nama_petrus_randanu kini memiliki
0 missing values. Ini menandakan bahwa seluruh tahap pembersihan data (termasuk
penanganan duplikat dan pengisian data hilang pada semua kolom) telah berhasil
diselesaikan, dan data kini secara struktural bersih dan siap untuk dianalisis lebih
lanjut.

Sekarang tidak ada lagi data missing atau NaN

**Menangani inaccurate value**

In [ ]:
Nama_petrus_randanu.jurusan.value_counts()

jurusan
Energi               21
Informatika          17
Teknik               12
Manajemen Energi     11
Pembangkit Energi     2
teknik                1
 energi               1
ManajemenEnergi       1
EnErGi                1
Teknik                1
ENG                   1
ENERGI                1
Name: count, dtype: int64

In [ ]:
Nama_petrus_randanu.umur.value_counts()

umur
23.0          15
25.0          10
20.0           9
24.0           9
22.0           8
19.0           7
21.0           4
23             2
150            1
twenty         1
-5             1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

Terdapat 2 kolom yang datanya tidak akurat atau  inaccurate value

In [ ]:
Nama_petrus_randanu['jurusan'] = Nama_petrus_randanu['jurusan'].str.lower().str.strip()
#ubah menjadi huruf kecil

In [ ]:
Nama_petrus_randanu.jurusan.value_counts()

jurusan
energi               24
informatika          17
teknik               14
manajemen energi     11
pembangkit energi     2
manajemenenergi       1
eng                   1
Name: count, dtype: int64

In [ ]:
#untuk memudahkan replacing maka di buatkan mapping jurusan sesuai dengan yg di inginkan, dengan kata-kata yg mirip di masukan ke jurusan yg seusai

mapping_jurusan = {
    "energi": "Pembangkit Energi",
    " energi ": "Pembangkit Energi",
    "ENERGI": "Pembangkit Energi",
    "EnErGi": "Pembangkit Energi",
    "eng": "Pembangkit Energi",
    "teknik": "Pembangkit Energi",
    "Teknik ": "Pembangkit Energi",
    "teknik ": "Pembangkit Energi",
    "manajemenenergi": "Manajemen Energi",
    "manajemen energi": "Manajemen Energi"
}

In [ ]:
Nama_petrus_randanu["jurusan"] = Nama_petrus_randanu["jurusan"].replace(mapping_jurusan)

In [ ]:
Nama_petrus_randanu["jurusan"] = Nama_petrus_randanu["jurusan"].str.title()

#kemablikan menjadi huruf besar

In [ ]:
Nama_petrus_randanu.jurusan.value_counts()

jurusan
Pembangkit Energi    41
Informatika          17
Manajemen Energi     12
Name: count, dtype: int64

In [ ]:
print("Hasil setelah normalisasi dan pemetaan:")
print(Nama_petrus_randanu['jurusan'].value_counts())

Hasil setelah normalisasi dan pemetaan:
jurusan
Energi              24
Informatika         20
Teknik              13
Manajemen Energi    12
teknik               1
ManajemenEnergi      1
 energi              1
EnErGi               1
Teknik               1
ENG                  1
ENERGI               1
Name: count, dtype: int64

PENJELASAN

Kode Nama_petrus_randanu ['jurusan'].str.lower().str.strip() ini adalah langkah krusial
dalam menyeragamkan dan membersihkan data teks pada kolom jurusan. Tujuannya
adalah mengatasi masalah inkonsistensi yang disebabkan oleh perbedaan kapitalisasi dan
spasi yang tidak disengaja, yang membuat komputer menganggap kategori yang sama
sebagai kategori yang berbeda. Metode .str.lower() berfungsi mengubah semua nama
jurusan menjadi huruf kecil secara keseluruhan.

Sekarang untuk inaccurate  value pada kolom jurusan sudah selesai dan tidak da yg type atau tidak terkelompok dengan benar

**Selanjutnya lakuakan untuk kolom nilai **

In [ ]:
Nama_petrus_randanu.umur.value_counts()

umur
23.0          19
25.0          12
24.0          11
20.0           9
22.0           8
19.0           7
21.0           4
150            1
-5             1
twenty         1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

PENJELASAN

pembersihan dan penyeragaman data numerik pada kolom umur.
Proses ini dimulai dengan membuat kamus pemetaan (mapping_umur) yang secara
eksplisit mendefinisikan bagaimana nilai yang tidak wajar atau tidak konsisten—seperti
teks ('twenty'), nilai di luar batas wajar (-5, 120), atau string dari NaN—harus diganti
menjadi nilai numerik yang valid (seperti 25). Kamus ini kemudian diaplikasikan
menggunakan fungsi .replace(), sehingga semua nilai umur yang bermasalah diubah
menjadi nilai yang wajar dan konsisten. Hasilnya, seperti yang ditunjukkan oleh
value_counts() dan dtype yang kini menjadi float64, membuktikan bahwa kolom umur
telah bersih total dan siap untuk dianalisis

di sini terlihat beberapa data yg tidak konsisten seperti (150, -5, twenty, 120,NaN_string, 21years

Selanjutnya lakukan seperti pada kolom jurusan , bisa di lakukan mapping atau di ganti satu persatu, karena di sini jumlah data yg inkonsisten hanya satum jadi bisa di replace saja

In [ ]:
mhs_df['umur'] = mhs_df['umur'].replace('twenty', 20)

#bisa di lakuakn replace satu persatu seperti ini
# dari sebelumnya twenty menjadi 20

In [ ]:
print(Nama_petrus_randanu['umur'].value_counts())

umur
23.0          19
25.0          12
24.0          11
20.0           9
22.0           8
19.0           7
21.0           4
150            1
-5             1
twenty         1
120            1
NaN_string     1
21years        1
Name: count, dtype: int64

PENJELASAN

menampilkan hasil akhir dari fungsi Nama_petrus_randanu.jurusan.value_co
unts() setelah seluruh proses pembersihan dan penyeragaman data pada kolom jurusan
selesai dilakukan. Hasilnya menunjukkan keberhasilan yang signifikan dalam
mengonsolidasikan dan merapikan kategori data. Nilai-nilai yang sebelumnya beragam
dan tidak konsisten akibat perbedaan kapitalisasi, spasi, atau penamaan. kini semuanya
telah digabungkan dan distandarisasi menjadi hanya tiga kategori utama: "Pembangkit
Energi" dengan total 41 entri, "Informatika" dengan 17 entri, dan "Manajemen Energi"
dengan 12 entri. Hasil ini memastikan bahwa penghitungan frekuensi kategori di kolom
jurusan kini akurat dan konsisten, sehingga data siap untuk analisis statistik atau
visualisasi yang valid.

Bisa di lakuakn replace satu persatu seperti di atas atau mapping kembali seperti jurusan sebelumnya

In [ ]:
"""mapping_umur = {
    'twenty': 20,
    '21years': 21,
    'NaN_string': np.nan,
    -5: np.nan,
    120: np.nan,
    150: np.nan
}
"""
#untuk nilai yang NaN_string, -5, 120, 150 bisa langsung di ganti dengan rata-rata umur atau di jadikan missing value, tetapi jika di jadikan missing value maka setelah ini anda akan mengganti missing value tersebut, jadi sebelum itu lebih baik  di cari rata-rata nya terlebih dahulu lalu di ganti pada mappingan ini

"mapping_umur = {\n    'twenty': 20,\n    '21years': 21,\n    'NaN_string': np.nan,\n    -5: np.nan,\n    120: np.nan,\n    150: np.nan\n}\n"

In [ ]:
Nama_petrus_randanu['umur'] = pd.to_numeric(Nama_petrus_randanu['umur'], errors='coerce')
Nama_petrus_randanu['umur'].mean()

np.float64(25.19178082191781)

PENJELASAN

fungsi .mean() digunakan untuk menghitung nilai rata-rata dari kolom umur yang kini
bersih, dan hasilnya adalah sekitar 22.49. Nilai rata-rata ini akan menjadi nilai imputasi
yang digunakan untuk mengisi data yang hilang pada kolom umur.

Sekarang setelah di konversi menjadi numerik maka di dapat nilai rata-rata, dan selanjutnya isikan pada mappinganya

In [ ]:
mapping_umur = {
    'twenty': 20,
    '21years': 21,
    'NaN_string': 25,
    -5: 25,
    120: 25,
    150: 25
}

In [ ]:
Nama_petrus_randanu['umur'] = Nama_petrus_randanu['umur'].replace(mapping_umur)

In [ ]:
print("Hasil setelah pemetaan:")
print(Nama_petrus_randanu['umur'].value_counts())
print(f"\nTipe data kolom 'umur' sekarang: {Nama_petrus_randanu['umur'].dtype}")

Hasil setelah pemetaan:
umur
23.0    19
25.0    15
24.0    11
20.0     9
22.0     8
19.0     7
21.0     4
Name: count, dtype: int64

Tipe data kolom 'umur' sekarang: float64

Sekarang kolom umur sudah tidak ada lagi data yg inaccruate,tetapi harus di pastikan lagi seperti di bawah ini

In [ ]:
Nama_petrus_randanu.isna().sum()
#ternyata terdapat 2 nilai yang NaN pada kolom umur

nim               0
nama              0
jurusan           2
umur              5
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

PENJELASAN

Setelah melakukan pembersihan untuk mengatasi nilai inaccurate atau tidak wajar
pada kolom umur melalui langkah mapping (yaitu mengganti nilai seperti 'twenty', -5,
120, dsb., dengan nilai yang lebih masuk akal), hasil verifikasi
Nama_petrus_randanu.isna().sum() menunjukkan bahwa kolom umur kini hanya
menyisakan 2 missing values atau NaN yang sebenarnya. Ini berarti, proses mapping
berhasil membersihkan nilai-nilai yang salah, namun gagal mengatasi dua baris yang
memang kosong total atau benar-benar hilang (NaN) dari sumber datanya

In [ ]:
Nama_petrus_randanu.head(50)
#untuk memastika bisa menggunakan sintaks di atas dengan masukan value baris yang ingin di lihat, cara ini juga bisa di lakukan untuk tail(50)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Teknik,25.0,59.5,82.0,2024-05-05
1,E0002,Budi,teknik,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Energi,25.0,56.2,78.0,2024-04-29
3,E0004,Dewi,Teknik,NaN,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999,65.0,2024-03-22
5,E0006,Fajar,Energi,21.0,-20,78.0,2024-06-21
6,E0007,Gina,Informatika,19.0,70.2,150.0,2024-06-25
7,E0008,Hendra,Energi,25.0,56.7,-10.0,2024-10-01
8,E0009,Ika,Informatika,25.0,58.2,83.0,2024-11-17
9,E0010,Joko,Teknik,23.0,62.7,69.0,2024-01-24
10,E0011,Kiki,Energi,25.0,66.6,70.0,05/02/2024
11,E0012,Lina,Informatika,22.0,66.1,NaN,2024-03-24
12,E0013,Maya,ManajemenEnergi,21.0,63.4,82.0,2024-12-25
13,E0014,Nando,Teknik,23.0,80.4,99.0,2024-05-05
14,E0015,Oki,energi,22.0,70.2,100.0,2024-04-22
15,E0016,Putu,Energi,25.0,85.7,68.0,2024-04-27
16,E0017,Qori,Teknik,25.0,67.6,82.0,2024-02-03
17,E0018,Rina,EnErGi,23.0,90.1,85.0,2024-04-18
18,E0019,Sari,Informatika,22.0,90.4,94.0,NaN
19,E0020,Tono,Informatika,20.0,64.9,100.0,2024-10-02
20,E0021,Uli,Teknik,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Energi,NaN,75.4,70.0,2024-01-25
22,E0023,Wawan,Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,NaN,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Teknik,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Teknik,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Energi,20.0,eighty,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Teknik,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Energi,23.0,NaN,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,NaN
37,E0038,Lulu,Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,NaN,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Teknik,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Teknik,24.0,95.0,65.0,2024-02-17

In [ ]:
Nama_petrus_randanu.tail(50)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
28,E0029,Cici,Teknik,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Energi,20.0,eighty,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Teknik,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Energi,23.0,NaN,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,NaN
37,E0038,Lulu,Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,NaN,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Teknik,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Teknik,24.0,95.0,65.0,2024-02-17
50,E0051,Zaki,Manajemen Energi,20.0,71.3,95.0,2024-04-19
51,E0052,Adel,Informatika,NaN,61.6,65.0,2024-07-18
52,E0053,Bagus,Manajemen Energi,25.0,86.4,83.0,2024-08-04
53,E0054,Cahyo,Energi,21years,62.6,78.0,2024-01-30
54,E0055,Dina,NaN,24.0,67.5,68.0,2024-10-26
55,E0056,Edo,Energi,23.0,ninety,98.0,2024-03-21
56,E0057,Fauzi,Energi,23.0,58.2,76.0,2024-02-05
57,E0058,Gita,Teknik,24.0,89.5,90.0,2024-03-02
58,E0059,Hadi,Informatika,23.0,78.8,70.0,2024-08-02
59,E0060,Ilham,Informatika,21.0,--,85.0,2024-05-02
60,E0061,Jaya,Informatika,22.0,60.2,84.0,2024-08-22
61,E0062,Kirana,Energi,25.0,92.4,65.0,2024-08-22
62,E0063,Lutfi,Teknik,19.0,76.5,97.0,2024-05-15
63,E0064,Mega,ENG,21.0,90.2,80.0,2024-07-08
64,E0065,Nadia,Informatika,NaN,72.5,99.0,2024-12-26
65,E0066,Oleh,ENERGI,23.0,94.4,98.0,2024-01-05
66,E0067,Putri,Energi,24.0,59.1,NaN,2024-05-15
67,E0068,Rafi,Informatika,19.0,84.7,74.0,2024-05-19
68,E0069,Salsa,Informatika,23.0,63.4,86.0,2024-04-14
69,E0070,Tasya,Manajemen Energi,23.0,74.5,68.0,2024-02-17
70,E0032,Ferry,Teknik,25.0,87.3,80.0,2024-01-30
71,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
72,E0062,Kirana,Energi,25.0,92.4,65.0,2024-08-22
73,E0057,Fauzi,Energi,23.0,58.2,76.0,2024-02-05
74,E0039,Mita,Energi,23.0,77.2,79.0,2024-01-04
75,E0069,Salsa,Informatika,23.0,63.4,86.0,2024-04-14
76,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
77,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24

Terdapat Missing value pada baris 21 dan 54

untuk itu bisa di lakukan replace lagi dengan memasukan rata-rata umur seperti sebelumnya

In [ ]:
Nama_petrus_randanu['umur'] = pd.to_numeric(Nama_petrus_randanu['umur'], errors='coerce')
Nama_petrus_randanu['umur'].mean() #mencari rata-rata

np.float64(25.19178082191781)

In [ ]:
Nama_petrus_randanu['umur'] = Nama_petrus_randanu['umur'].fillna(22) #isi dengan nilai rata-rata

In [ ]:
Nama_petrus_randanu.isna().sum()

nim               0
nama              0
jurusan           2
umur              0
nilai_akhir       2
kehadiran_pct     2
tanggal_daftar    2
dtype: int64

PENJELASAN

langkah terakhir dalam menyelesaikan seluruh masalah data
yang hilang (missing values) di DataFrame Anda. Prosesnya dimulai dengan
menghitung rata-rata (mean) kolom umur yang sudah dibersihkan, didapatkan nilai
22.43. Kemudian, kode Nama_petrus_randanu['umur'].fillna(22) dieksekusi. Kode ini
menggunakan teknik imputasi untuk mengisi dua missing values yang tersisa di kolom
umur dengan nilai 22 (pembulatan dari nilai rata-rata). Setelah pengisian ini, fungsi
Nama_petrus_randanu.isna().sum() dijalankan sebagai validasi akhir. Hasilnya
menunjukkan bahwa semua kolom dalam DataFrame nim, nama, jurusan, umur,
nilai_akhir, kehadiran_pct, dan tanggal_daftar kini telah memiliki 0 missing values. Ini
menandakan bahwa seluruh tahap pembersihan data telah berhasil.

Setelah di cek sudah tidak ada lagi data yang missing pada semua kolom data

In [ ]:
Nama_petrus_randanu.duplicated().sum()

np.int64(8)

PENJELASAN

Fungsi Nama_petrus_randanu.duplicated().sum() digunakan untuk menghitung total
baris yang merupakan duplikat. Output berupa np.int64(8) menegaskan bahwa setelah
semua langkah pembersihan data sebelumnya (termasuk penghapusan duplikat di awal
proses), jumlah baris duplikat yang terdeteksi adalah nol

Untuk pulikat juga sama tidak ada data yang duplikat

Untuk memverifikasi bisa show head() dan tail() seperti di bawah ini atau count duplicates() dan isnan()

In [ ]:
Nama_petrus_randanu.head(55)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Teknik,150.0,59.5,82.0,2024-05-05
1,E0002,Budi,teknik,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Energi,-5.0,56.2,78.0,2024-04-29
3,E0004,Dewi,Teknik,22.0,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999,65.0,2024-03-22
5,E0006,Fajar,Energi,21.0,-20,78.0,2024-06-21
6,E0007,Gina,Informatika,19.0,70.2,150.0,2024-06-25
7,E0008,Hendra,Energi,25.0,56.7,-10.0,2024-10-01
8,E0009,Ika,Informatika,120.0,58.2,83.0,2024-11-17
9,E0010,Joko,Teknik,23.0,62.7,69.0,2024-01-24
10,E0011,Kiki,Energi,25.0,66.6,70.0,05/02/2024
11,E0012,Lina,Informatika,22.0,66.1,NaN,2024-03-24
12,E0013,Maya,ManajemenEnergi,21.0,63.4,82.0,2024-12-25
13,E0014,Nando,Teknik,23.0,80.4,99.0,2024-05-05
14,E0015,Oki,energi,22.0,70.2,100.0,2024-04-22
15,E0016,Putu,Energi,25.0,85.7,68.0,2024-04-27
16,E0017,Qori,Teknik,25.0,67.6,82.0,2024-02-03
17,E0018,Rina,EnErGi,23.0,90.1,85.0,2024-04-18
18,E0019,Sari,Informatika,22.0,90.4,94.0,NaN
19,E0020,Tono,Informatika,20.0,64.9,100.0,2024-10-02
20,E0021,Uli,Teknik,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Energi,22.0,75.4,70.0,2024-01-25
22,E0023,Wawan,Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,NaN,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Teknik,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Teknik,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Energi,20.0,eighty,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Teknik,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Energi,23.0,NaN,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,NaN
37,E0038,Lulu,Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,NaN,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Teknik,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Teknik,24.0,95.0,65.0,2024-02-17
50,E0051,Zaki,Manajemen Energi,20.0,71.3,95.0,2024-04-19
51,E0052,Adel,Informatika,22.0,61.6,65.0,2024-07-18
52,E0053,Bagus,Manajemen Energi,25.0,86.4,83.0,2024-08-04
53,E0054,Cahyo,Energi,22.0,62.6,78.0,2024-01-30
54,E0055,Dina,NaN,24.0,67.5,68.0,2024-10-26

In [ ]:
Nama_petrus_randanu.tail()

      nim   nama      jurusan  umur nilai_akhir  kehadiran_pct tanggal_daftar
73  E0057  Fauzi       Energi  23.0        58.2           76.0     2024-02-05
74  E0039   Mita       Energi  23.0        77.2           79.0     2024-01-04
75  E0069  Salsa  Informatika  23.0        63.4           86.0     2024-04-14
76  E0031   Eros  Informatika  23.0        68.0           66.0     2024-02-27
77  E0026   Zara  Informatika  24.0        90.4           82.0     2024-11-24

In [ ]:
Nama_petrus_randanu.tail()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             70 non-null     object
 1   nama            70 non-null     object
 2   jurusan         70 non-null     object
 3   umur            70 non-null     float64
 4   nilai_akhir     70 non-null     float64
 5   kehadiran_pct   70 non-null     float64
 6   tanggal_daftar  70 non-null     object
dtypes: float64(3), object(4)
memory usage: 6.4+ KB

JIka di lihat pada info, maka semua jumlah data sama yaitu 70, maka proses Pembersihan data sudah selesai

Export data yang sudah di bersihkan menjadi file csv, menggunakan script berikut ini

In [ ]:
Nama_petrus_randanu.to_csv("mahasiswa_clean.csv", index=False)

Lalu lakukan Dodownload file csv yang sudah di export sebelumnya

In [ ]:
from google.colab import files
files.download("mahasiswa_clean.csv")

Bandingkan hasil data csv sebelumnya dengan csv yang sudah di bersihkan
bisa di buka menggunakan excel / spreadsheet untuk membandingaknya

**Silahkan di jelskan langkah-langkah dan hasil latihan pada laporan**

---

In [ ]:
test_df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
Nama_petrus_randanu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nim             78 non-null     object
 1   nama            78 non-null     object
 2   jurusan         76 non-null     object
 3   umur            78 non-null     float64
 4   nilai_akhir     76 non-null     object
 5   kehadiran_pct   76 non-null     float64
 6   tanggal_daftar  76 non-null     object
dtypes: float64(2), object(5)
memory usage: 4.4+ KB

In [ ]:
Nama_petrus_randanu.describe()

             umur  kehadiran_pct
count   78.000000      76.000000
mean    24.987179      81.815789
std     18.479538      17.285609
min     -5.000000     -10.000000
25%     21.000000      72.250000
50%     23.000000      82.000000
75%     24.000000      92.250000
max    150.000000     150.000000

In [ ]:
Nama_petrus_randanu.head(60)

,nim,nama,jurusan,umur,nilai_akhir,kehadiran_pct,tanggal_daftar
0,E0001,Aldi,Teknik,150.0,59.5,82.0,2024-05-05
1,E0002,Budi,teknik,20.0,84.5,99.0,2024-02-14
2,E0003,Citra,Energi,-5.0,56.2,78.0,2024-04-29
3,E0004,Dewi,Teknik,22.0,63.0,99.0,2024-08-02
4,E0005,Eka,Manajemen Energi,22.0,999,65.0,2024-03-22
5,E0006,Fajar,Energi,21.0,-20,78.0,2024-06-21
6,E0007,Gina,Informatika,19.0,70.2,150.0,2024-06-25
7,E0008,Hendra,Energi,25.0,56.7,-10.0,2024-10-01
8,E0009,Ika,Informatika,120.0,58.2,83.0,2024-11-17
9,E0010,Joko,Teknik,23.0,62.7,69.0,2024-01-24
10,E0011,Kiki,Energi,25.0,66.6,70.0,05/02/2024
11,E0012,Lina,Informatika,22.0,66.1,NaN,2024-03-24
12,E0013,Maya,ManajemenEnergi,21.0,63.4,82.0,2024-12-25
13,E0014,Nando,Teknik,23.0,80.4,99.0,2024-05-05
14,E0015,Oki,energi,22.0,70.2,100.0,2024-04-22
15,E0016,Putu,Energi,25.0,85.7,68.0,2024-04-27
16,E0017,Qori,Teknik,25.0,67.6,82.0,2024-02-03
17,E0018,Rina,EnErGi,23.0,90.1,85.0,2024-04-18
18,E0019,Sari,Informatika,22.0,90.4,94.0,NaN
19,E0020,Tono,Informatika,20.0,64.9,100.0,2024-10-02
20,E0021,Uli,Teknik,24.0,78.4,90.0,2024-07-04
21,E0022,Vina,Energi,22.0,75.4,70.0,2024-01-25
22,E0023,Wawan,Energi,20.0,80.1,92.0,2024-11-01
23,E0024,Xena,Informatika,22.0,70.3,94.0,2024-09-27
24,E0025,Yudi,NaN,23.0,89.4,65.0,2024-12-14
25,E0026,Zara,Informatika,24.0,90.4,82.0,2024-11-24
26,E0027,Arif,Energi,19.0,66.7,75.0,24 Nov 2024
27,E0028,Bima,Teknik,24.0,90.0,81.0,2024-09-13
28,E0029,Cici,Teknik,23.0,91.5,84.0,2024-11-23
29,E0030,Dani,Energi,20.0,eighty,75.0,2024-10-03
30,E0031,Eros,Informatika,23.0,68.0,66.0,2024-02-27
31,E0032,Ferry,Teknik,25.0,87.3,80.0,2024-01-30
32,E0033,Gilang,Energi,23.0,NaN,70.0,2024-09-05
33,E0034,Hani,Manajemen Energi,25.0,76.3,73.0,2024-03-06
34,E0035,Indra,Manajemen Energi,23.0,61.6,98.0,2024-11-06
35,E0036,Jeni,Informatika,20.0,92.2,77.0,2024-12-31
36,E0037,Kris,Manajemen Energi,22.0,94.8,88.0,NaN
37,E0038,Lulu,Energi,19.0,64.9,69.0,2024-06-22
38,E0039,Mita,Energi,23.0,77.2,79.0,2024-01-04
39,E0040,Nina,Energi,24.0,80.2,79.0,09-17-2024
40,E0041,Omar,Informatika,25.0,NaN,97.0,2024-05-01
41,E0042,Pia,Manajemen Energi,24.0,74.4,99.0,2024-03-08
42,E0043,Rico,Energi,20.0,86.4,91.0,2024-04-07
43,E0044,Sinta,Manajemen Energi,19.0,81.4,87.0,2024-08-04
44,E0045,Tari,Energi,22.0,89.6,68.0,2024-12-10
45,E0046,Umar,Teknik,19.0,71.1,86.0,2024-02-25
46,E0047,Vita,Manajemen Energi,20.0,62.6,93.0,2024.06.28
47,E0048,Widi,Manajemen Energi,20.0,66.1,80.0,2024-02-08
48,E0049,Xul,Energi,25.0,89.5,100.0,May 22 2024
49,E0050,Yosef,Teknik,24.0,95.0,65.0,2024-02-17
50,E0051,Zaki,Manajemen Energi,20.0,71.3,95.0,2024-04-19
51,E0052,Adel,Informatika,22.0,61.6,65.0,2024-07-18
52,E0053,Bagus,Manajemen Energi,25.0,86.4,83.0,2024-08-04
53,E0054,Cahyo,Energi,22.0,62.6,78.0,2024-01-30
54,E0055,Dina,NaN,24.0,67.5,68.0,2024-10-26
55,E0056,Edo,Energi,23.0,ninety,98.0,2024-03-21
56,E0057,Fauzi,Energi,23.0,58.2,76.0,2024-02-05
57,E0058,Gita,Teknik,24.0,89.5,90.0,2024-03-02
58,E0059,Hadi,Informatika,23.0,78.8,70.0,2024-08-02
59,E0060,Ilham,Informatika,21.0,--,85.0,2024-05-02